Refactor
MAKWritingHouse/Random-Quote pull request #7
Opened 2023-08-31 17:51 UTC by MAKWritingHouse

config:
- eslint
- prettier
- jest
- APIs
handle APIs from next apis

2023-09-05 18:16 UTC, makstyle119 submitted a review, later dismissed
Refactor

2023-09-14 09:21 UTC, MAKDevelopmentHouse commented on package-lock.json
remove `package-lock.json`

2023-09-14 09:21 UTC, MAKDevelopmentHouse requested changes
code is not documented

2023-10-01 18:35 UTC, makstyle119 approved these changes, later dismissed
Refactor

2023-10-01 18:41 UTC, MAKDevelopmentHouse approved these changes, later dismissed
Refactor

2023-10-01 18:52 UTC, MAKDevelopmentHouse approved these changes
**approved!**

2023-10-01 18:54 UTC, makstyle119 approved these changes
**Approved !**

2023-10-01 19:11 UTC, merged